// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRVO7FU4Bq-HpumgGTN8j0O36tKCeFXw',
    appId: '1:567376228596:web:6669461dc71916293daea1',
    messagingSenderId: '567376228596',
    projectId: 'marketplaceproject-a018b',
    authDomain: 'marketplaceproject-a018b.firebaseapp.com',
    storageBucket: 'marketplaceproject-a018b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEPKC4w53aegSh9JhUHa1NZriL_T6G8o',
    appId: '1:567376228596:android:6f5785e8968043de3daea1',
    messagingSenderId: '567376228596',
    projectId: 'marketplaceproject-a018b',
    storageBucket: 'marketplaceproject-a018b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLAZlgn8sYTBWBAQiHqisYNhI-w0yi1XU',
    appId: '1:567376228596:ios:535b4e33323a632b3daea1',
    messagingSenderId: '567376228596',
    projectId: 'marketplaceproject-a018b',
    storageBucket: 'marketplaceproject-a018b.appspot.com',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLAZlgn8sYTBWBAQiHqisYNhI-w0yi1XU',
    appId: '1:567376228596:ios:535b4e33323a632b3daea1',
    messagingSenderId: '567376228596',
    projectId: 'marketplaceproject-a018b',
    storageBucket: 'marketplaceproject-a018b.appspot.com',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRVO7FU4Bq-HpumgGTN8j0O36tKCeFXw',
    appId: '1:567376228596:web:2584a4b456c9d7e23daea1',
    messagingSenderId: '567376228596',
    projectId: 'marketplaceproject-a018b',
    authDomain: 'marketplaceproject-a018b.firebaseapp.com',
    storageBucket: 'marketplaceproject-a018b.appspot.com',
  );
}
